ALTER TABLE Accounts ADD COLUMN IF NOT EXISTS external_account_id VARCHAR(255);
ALTER TABLE Accounts ADD COLUMN IF NOT EXISTS account_type VARCHAR(50);
ALTER TABLE Accounts ADD COLUMN IF NOT EXISTS color_hex VARCHAR(7);
ALTER TABLE Accounts ADD COLUMN IF NOT EXISTS is_archived BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE Accounts ADD COLUMN IF NOT EXISTS last_synced_at TIMESTAMPTZ;
ALTER TABLE Accounts ADD COLUMN IF NOT EXISTS currency VARCHAR(3) NOT NULL DEFAULT 'RUB';
